### Numpy

In [3]:
!pip install numpy

## Conda install numpy

In [1]:
## importing numpy

import numpy as np

In [2]:
my_lst=[1,2,3,4,5]
arr=np.array(my_lst)

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
print(arr)

[1 2 3 4 5]


In [7]:
arr.shape

(5,)

In [20]:
## Multidimensional Array

my_list1=[1,2,3,4,5]
my_list2=[6,7,8,9,0]
my_list3=[11,12,13,14,15]

arr1=np.array([my_list1,my_list2,my_list3])

print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9  0]
 [11 12 13 14 15]]


In [9]:
type(arr1)

numpy.ndarray

In [11]:
arr1.shape

(3, 5)

In [17]:
arr1.reshape(1,15)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9,  0, 11, 12, 13, 14, 15]])

### Indexing

In [18]:
## indexing/accessing array elements

arr=np.array([1,2,3,4,5,6,7,8,9])

arr[3]

4

In [19]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9,  0],
       [11, 12, 13, 14, 15]])

In [22]:
arr1[:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9,  0],
       [11, 12, 13, 14, 15]])

In [43]:
arr1[2,4]

15

In [25]:
arr1[2:2]

array([], shape=(0, 5), dtype=int32)

In [26]:
arr1[0:2,:]

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [31]:
arr1[1:2]

array([[6, 7, 8, 9, 0]])

In [33]:
arr1[1:,3:]

array([[ 9,  0],
       [14, 15]])

In [37]:
arr1[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [62]:
arr=np.arange(1,9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [63]:
arr=np.arange(1,9,2)
arr

array([1, 3, 5, 7])

In [66]:
##np.linspace
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [67]:
##Copy() function and broadcasting

arr=[1,2,3,4,5,6,7,8,9]

In [68]:
arr

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [70]:
arr[3:]

[4, 5, 6, 7, 8, 9]

In [76]:
arr[3:]=100

TypeError: can only assign an iterable

In [77]:
arr<2

TypeError: '<' not supported between instances of 'list' and 'int'

In [96]:
value=2
type(value)

type(arr)

arr<2

TypeError: '<' not supported between instances of 'list' and 'int'

In [79]:
#Print A Simple Payroll Report
name = ['Hai', 'Bell', 'Cindy', 'Danny', 'Eddy', 'Felicia', 'Gigi', 'Apple','Indie','Jacon','Kim','Lim']
hours = [10, 45, 60, 70, 20, 35, 80, 30, 65, 55, 15, 90]
rate = 9.5

In [87]:
n = len(name)
 
print('\n\t    Payroll Report\n')
print('No.\tEmployee Name\tHours\tSalary(RM)')


	    Payroll Report

No.	Employee Name	Hours	Salary(RM)


In [85]:
print(n)

12


In [90]:
for i in range(n):
    if hours[i] <= 40:
        wage = hours*rate
    elif  hours[i] <= 60:
        wage = 380 + (hours[i] + 40) * rate * 1.5
    else:
        665 + (hours[i] + 60) * rate * 2.0
         
 
    print('%d\t%s\t%d\t%s' % (i+1, name[i], hours[i], wage))

TypeError: can't multiply sequence by non-int of type 'float'